# Generated by Django 5.1.2 on 2025-02-24 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('about_course', models.TextField(blank=True, null=True)),
                ('course_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Read More',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('max_student', models.IntegerField(default=10)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('course_photo', models.ImageField(blank=True, null=True, upload_to='courses/course_photo/%Y/%m')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('teacher', models.ManyToManyField(blank=True, default=None, to='teachers.teacher')),
                ('read_more', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teachers.readmore')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('start_from', models.DateField(null=True)),
                ('duration', models.IntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('max_student', models.IntegerField(default=10)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('lang', models.CharField(choices=[('1', 'UZ'), ('2', 'RU'), ('3', 'EN')], max_length=20, null=True)),
                ('group_photo', models.ImageField(blank=True, null=True, upload_to='courses/course_photo/%Y/%m')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teachers.course')),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teachers.teacher')),
                ('read_more', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teachers.readmore')),
            ],
        ),
    ]
