# Generated by Django 5.1.2 on 2025-02-24 04:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_readmore_course_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='langs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'UZ'), ('2', 'RU'), ('3', 'EN')], max_length=5, null=True),
        ),
    ]
