# Generated by Django 5.1.6 on 2025-04-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_course_langs'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmore',
            name='course_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teachers.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=3, help_text='3'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='1100000', max_digits=9, null=True),
        ),
    ]
